### PR TITLE
Adding `-d` to docker-compose to run in background

### PR DESCRIPTION
**Pull request by joedborg**
...otherwise the cluster comes up in the foreground and you have to kill it before relaunching with `-d`.

### CODE REVIEW

**Comment by stuartlangridge** [comment]
I quite like it running in the foreground, but maybe I'm weird. If you adjust the README patch to note that it'll run in the background now, I'd be happy with it. (Also can you remove the whitespace cleanup? That should be done, definitely, but ideally not in the same patch with something more substantive.)

**Comment by joedborg** [comment]
No problem on the white space!

My train of though is that, if you’re following the step by step, you’ve blocked your terminal by compose, but totally agree that this is a matter of taste.

**Comment by joedborg** [comment]
(Will open new PR with changes)

**Comment by stuartlangridge** [comment]
Cool stuff. Maybe add a note explaining how to kill the background-running setup when changing the readme?

**Comment by jeremy-lq** [comment]
@stuartlangridge What do you see as the benefit of running in the foreground, and do you think it's a good default?

**Comment by stuartlangridge** [comment]
Benefits: we don't need to document how to _stop_ running (it's ctrl-C), and you can see what it's doing without having to run a logs command. Neither of these are dealbreakers, certainly, but they're the reasons I run it in the foreground. So if we added this, I wouldn't use it locally, but that's fine -- it's really what we're best to advise people to do generally to avoid surprising them. (Note that this is only a patch to the README, not to actual code, so it's just about what's the least confusing instruction.)

**Pull request closed without merging**
